# ==========================================
# Airport Management API — Configuración principal
# Perfil activo por defecto: dev (H2 en memoria)
# ==========================================
spring.application.name=airport-management
spring.profiles.active=dev

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Server
server.port=8080
